### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by PathToSharePoint** [MaTeMaTuK/gantt-task-react#1]
I just started testing your Gantt solution. I like the professional, slick look.

A first thing I tried is start date = end date. In this case the task doesn't get displayed, see example with "developing":

![image](https://user-images.githubusercontent.com/40323257/93724136-5e3df000-fb59-11ea-89a2-7116af869cdd.png)

I would suggest to add a special type called "Milestone" for such tasks. It is usually represented as a diamond shape in Gantts.

**Comment by MaTeMaTuK** [comment]
Hi @PathToSharePoint,
Thanks for your feedback.
I agree with you and I have a plan about tasks with very small duration. Maybe I should represent them as a box, without end and start time controls.
Milestone is also possible to do.

**Comment by PathToSharePoint** [comment]
Thanks for looking into this! 

I think the point of the usual diamond is to avoid confusion with short tasks, especially in monthly views. btw that brings up an interesting question (more a matter of convention): when a task starts and ends on the same day, does the duration count as one day or zero?

Another minor point, I would expect the tooltip to switch to the left of the bar for the latest tasks.

**Comment by MaTeMaTuK** [comment]
1) Diamond shape is for milestone only. Other solutions use rectangle shape as well
![image](https://user-images.githubusercontent.com/26743903/93804200-a25eec80-fc4e-11ea-85d0-1ab29678658a.png)
2) Yes. It's nice to have hour duration for diurnal task
3) I don't understand left tooltip concept

**Comment by PathToSharePoint** [comment]
Sorry I should have included a screenshot. See how the tooltip gets cut off, I would expect it to automatically reposition on the other side of the bar where there is more room. The same way you auto-position above or below.

![image](https://user-images.githubusercontent.com/40323257/93808321-acf29500-fc00-11ea-9491-ce5f377934c1.png)

**Comment by MaTeMaTuK** [comment]
Hi @PathToSharePoint, 
I'm working on your task however I don`t have enough time until Christmas. FYI

**Comment by PathToSharePoint** [comment]
Thanks for the update @MaTeMaTuK . I am looking forward to testing the next version!

**Comment by MaTeMaTuK** [comment]
Hi @PathToSharePoint,
Please check the new release

**Comment by PathToSharePoint** [comment]
Thanks for the update, I'll give it a try. The live demo looks great!
