### ISSUE TITLE
Broken arrows

### ISSUE THREAD

**Issue by PathToSharePoint** [MaTeMaTuK/gantt-task-react#13]
I am going to use this nice Gantt for a solution, and I have a question: why so many broken lines (see screenshot below)? Wouldn't it be easier to just go straight?
![image](https://user-images.githubusercontent.com/40323257/126041636-cfdeaa5f-8d08-4d88-9e9f-a1cf5e66c5b4.png)

I was thinking maybe something like this:
![image](https://user-images.githubusercontent.com/40323257/126041986-6096f503-cab0-4a3f-aa72-22cf4240e1fe.png)

Thanks!

**Comment by MaTeMaTuK** [comment]
Hi @PathToSharePoint,
I will check how it looks like.

**Comment by MaTeMaTuK** [comment]
Arrow visual fix has been published with new release

**Comment by PathToSharePoint** [comment]
I checked out the live demo, looks great!
