### ISSUE TITLE
Needed grouping of tasks based on projects

### ISSUE THREAD

**Issue by afjal-arlab** [MaTeMaTuK/gantt-task-react#14]
Hi, 

This is a feature request. OR if anyone already has already implemented this than please help.

**What I want to achieve:**
Grouping of the tasks based on the project. Means, I want to have collapse and expanded view of tasks based on the projects.

Example:
<img width="915" alt="Screenshot 2021-07-27 at 11 43 49 AM" src="https://user-images.githubusercontent.com/72443768/127104833-87735831-d455-48f1-b2db-77037fec4925.png">

If this package already have that functionality then please let me know. If not please suggest an approach.

Thanks in advance.

**Comment by MaTeMaTuK** [comment]
Hi @afjal-arlab,
I will take a look

**Comment by MaTeMaTuK** [comment]
Hello,
I have added visual grouping. Please check the demo

**Comment by UserManagedSolutions** [comment]
@MaTeMaTuK My two cents: the result in the demo doesn't look like what @afjal-arlab was describing or what is usually done in Gantts. Usually you would expect an expand-collapse feature when there is a hierarchy (tasks within a project, or subtasks within a summary task). In the demo, the "grouping" just hides dependent tasks.

**Comment by MaTeMaTuK** [comment]
Thanks, @UserManagedSolutions.
I should remove hiding for all tasks by default now 😅
Maybe the best option is keep hiding feature for project type only. 
By the way, developer control component state and he able to update project record with his/her wishes

**Comment by afjal-arlab** [comment]
Thanks, @MaTeMaTuK 
Although, it makes sense in some cases, to hide the dependent tasks because I made those dependent on other tasks. So I'm expecting them to be connected with parent-dependent tasks.

And if your tasks are not dependent. Then it will keep hiding tasks for the project type only, which is working fine as of now.
So in both cases, it's fine whether you remove this for tasks or add props to manage this. 
In my case, expand-collapse feature is working as expected, as my tasks are not dependent on each other. They're just under the same project.

And thanks a lot for the quick response and all the help :)

**Comment by VikariiCGI** [comment]
Good. I keep hide mechanism for project only for now.
Maybe I will extend this feature after.
