### ISSUE TITLE
Hide days name (Mon, Tue, Wed, etc..) option

### ISSUE THREAD

**Issue by jrmygp** [MaTeMaTuK/gantt-task-react#154]
Hey @MaTeMaTuK  is there any option to hide the days name? Thanks!

**Comment by MickaelAustoni** [comment]
Same question, like the `readme` screen when `ViewMode.Day `is provided for exemple

**Comment by HyunM** [comment]
In React, you can use like that. (Sat, 15 -> 15)

`useEffect(() => {
		setTimeout(() => {
			let elementsOfCalendar = document.getElementsByClassName('_9w8d5');
			for (let i = 0; i < elementsOfCalendar.length; i++) {
				elementsOfCalendar[i].innerHTML = elementsOfCalendar[i].innerHTML
					.substring(4)
					.trim();
			}
		}, 1);
	}, []);`

**Comment by shahriarhossain** [comment]
@HyunM : When I update the innerHTML it updates the date, however, all those innerHtml record gets hidden as well. Any idea why?
'
