### ISSUE TITLE
it is failed when running the example 

### ISSUE THREAD

**Issue by sandy105** [MaTeMaTuK/gantt-task-react#172]
I ran in a issue when npm install: 
npm ERR! code 127
npm ERR! path /Users/yanteng/Projects/FAW/libs/gantt-task-react-main
npm ERR! command failed
npm ERR! command sh -c run-s build
npm ERR! sh: run-s: command not found

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/yanteng/.npm/_logs/2023-03-16T07_51_34_395Z-debug-0.log

could someone know how to fix it?

**Comment by maltinho8** [comment]
Did you navigate into the example folder first?

**Comment by sandy105** [comment]
Yes， I fixed it by using this command： 
npm install create-react-app

**Comment by sandy105** [comment]
npm install create-react-app

**Comment by Lilja** [comment]
Also ran into this error. Npm installing the root repository first and then the example directory worked for me.
