### ISSUE TITLE
locale is set To Locale, but the values of the fields From and to do not also become local

### ISSUE THREAD

**Issue by dsbruce** [MaTeMaTuK/gantt-task-react#189]
locale is set To Locale, but the values of the fields From and to do not also become local
![image](https://github.com/MaTeMaTuK/gantt-task-react/assets/90232157/596cd64c-2be7-4d08-9e1d-73ae716e36c7)

**Comment by dsbruce** [comment]
Sorry, no F5 refresh caused

**Comment by zhangxu1123** [comment]
> locale is set To Locale, but the values of the fields From and to do not also become local ![图像](https://user-images.githubusercontent.com/90232157/239496395-596cd64c-2be7-4d08-9e1d-73ae716e36c7.png)

请问怎么设置成中文的，我看他这个好像没支持国际化

**Comment by jon1301** [comment]
同问，如何中文的？ 难道是修改源码

**Comment by mraiguo** [comment]
看源码的类型备注，这么设置即可
![image](https://github.com/MaTeMaTuK/gantt-task-react/assets/22299421/eb8508dc-d4e5-40cc-9167-806e1c17c2bc)
![image](https://github.com/MaTeMaTuK/gantt-task-react/assets/22299421/d3384536-b6a0-4aa3-91f4-898e935b0c46)

**Comment by mraiguo** [comment]
> > locale is set To Locale, but the values of the fields From and to do not also become local ![图像](https://user-images.githubusercontent.com/90232157/239496395-596cd64c-2be7-4d08-9e1d-73ae716e36c7.png)
> 
> 请问怎么设置成中文的，我看他这个好像没支持国际化

看源码的类型备注，这么设置即可 ![image](https://user-images.githubusercontent.com/22299421/267888450-eb8508dc-d4e5-40cc-9167-806e1c17c2bc.png) ![image](https://user-images.githubusercontent.com/22299421/267888573-d3384536-b6a0-4aa3-91f4-898e935b0c46.png)
