### ISSUE TITLE
Milestone Diamond Shape

### ISSUE THREAD

**Issue by shivang10** [MaTeMaTuK/gantt-task-react#2]
I am using this library in my project but for the milestone, the diamond shape does not come. It is the same as for the issues, i.e. the horizontal bar.

![gantt chart](https://user-images.githubusercontent.com/22600838/108725528-7e307000-754c-11eb-805d-a2b3d8672f07.png)

This is the output that I am getting.
So how can I get the diamond shape?

**Comment by MaTeMaTuK** [comment]
Hi @shivang10,
I'm working on milestones

**Comment by MaTeMaTuK** [comment]
Hi @shivang10,
Please check the new release

**Comment by shivang10** [comment]
Thanks a lot, @MaTeMaTuK for this.
