### ISSUE TITLE
How to custom TaskList content ?

### ISSUE THREAD

**Issue by hungga1711** [MaTeMaTuK/gantt-task-react#20]
Is it possible to custom TaskListHeader text (change `Name, From, To` to another text) ? 
And How to custom date format ? (I want to use `DD/MM` format).
Thanks.

**Comment by MaTeMaTuK** [comment]
Hi @hungga1711,
You can override your TaskListTable.
Examples:
https://github.com/MaTeMaTuK/gantt-task-react/blob/main/src/components/task-list/task-list.tsx
https://github.com/MaTeMaTuK/pcf-universal-gantt-chart/blob/master/UniversalGanttChartComponent/components/task-list-table.tsx
