### ISSUE TITLE
Project / Parent Relationship bug?

### ISSUE THREAD

**Issue by Freem11** [MaTeMaTuK/gantt-task-react#30]
Seems like the "project" parent task feature doesn't work?
I have tried the following: 
project task:
 {
    start: new Date(2022, 0, 3),
    end: new Date(2022, 0, 30),
    name: Phase 1",
    id: "big",
    type: "project",
    progress: 100,
    dependencies: [],
    styles: { progressColor: "blue", progressSelectedColor: "#ff9e0d", barCornerRadius: 5 },
    hideChildren: true,
  },

child task:
 {
    start: new Date(2022, 0, 3),
    end: new Date(2022, 0, 17),
    name: "Task 1",
    id: 1,
    type: "task",
    progress: 100,
    dependencies: [],
    styles: { progressColor: "blue", progressSelectedColor: "#ff9e0d", barCornerRadius: 5 },
    project: "big",
  },

but the Gantt isn't recognizing that Project Name: phase 1, Id: big has child Name: Task 1, if i have set this up wrong please let me know but as far as i can tell it's just not working as it should based on what i have seen in the documentation / example

**Comment by Freem11** [comment]
eventually sorted it, however the instructions could do with enhancing there is quite a bit im having to dig way past the current scope of the instructions to figure out that the demo shows off

**Comment by lems3** [comment]
@Freem11 How did you solve this ? I have the same issue.
