### ISSUE TITLE
Show Day Names (sun, mon, tue, wed, etc..) instead of number

### ISSUE THREAD

**Issue by panjiggm** [MaTeMaTuK/gantt-task-react#34]
Hi, I want to display the name of the day, is it possible?

**Comment by MaTeMaTuK** [comment]
Hi @panjiggm,
I can add the option for this.

**Comment by MaTeMaTuK** [comment]
Hi @panjiggm,
I have added day of week in several vies. Please check the latest version.

**Comment by panjiggm** [comment]
hi @MaTeMaTuK, 
Thanks for the update
