### ISSUE TITLE
install

### ISSUE THREAD

**Issue by shrai31** [MaTeMaTuK/gantt-task-react#35]
npm install gantt-task-react
![Screenshot from 2022-01-04 00-08-19](https://user-images.githubusercontent.com/44105776/147967031-ebb4cb49-8ce8-4182-8020-2dd42d761e7f.png)

**Comment by MaTeMaTuK** [comment]
Hi @shrai31,
gantt uses old version of react. Im going to use 17.0.2 version in new release.

**Comment by MaTeMaTuK** [comment]
Hi, please try the latest version

**Comment by TomasHubelbauer** [comment]
FYI this error still pops up in the latest release. I had to use `--use-legacy-deps` to make it work with React 18.
