### ISSUE TITLE
view current date after loading page with gant

### ISSUE THREAD

**Issue by uVisionM** [MaTeMaTuK/gantt-task-react#39]
Hi, 
if i have a lot of date with startDate for example 1-1-2018, page with this gant after loading shows the start of the chart from that point on and I have to scroll to 2022. 
How to display a graph, e.g. with the current month displayed after the page has been loaded?

**Comment by MaTeMaTuK** [comment]
Hi,
I think it`s good idea to have the jump to now action. 
I will try to add this.

**Comment by uVisionM** [comment]
Cool. Control scroll or cut for example to last two months also sounds ok :)

**Comment by MaTeMaTuK** [comment]
Hi @uVisionM,
You may try new viewDate param in the latest version.
