### ISSUE TITLE
Limited Height

### ISSUE THREAD

**Issue by james-hafer** [MaTeMaTuK/gantt-task-react#4]
When setting a height limit the chart loses the ability to scroll horizontally. You can view the issue on the demo page as you will not be able to scroll to 'Party Time'.

**Comment by MaTeMaTuK** [comment]
Hi @james-hafer ,
Thank you for report. I will take a look.

**Comment by MaTeMaTuK** [comment]
Hi,
Could you please test demo again?
https://matematuk.github.io/gantt-task-react/
If everything is fine I will publish the next version

**Comment by james-hafer** [comment]
Hi @MaTeMaTuK,
Thank you for looking into this, everything appears to be working as expected!

**Comment by MaTeMaTuK** [comment]
v0.3.1 has been published to npm
