### ISSUE TITLE
Hover Text with Single Task

### ISSUE THREAD

**Issue by james-hafer** [MaTeMaTuK/gantt-task-react#5]
When adding in the ability to filter by owner, there is the scenario where there may be a single task on the chart. If this is the case, the hover text gets cut off. Please see screenshots attached and let me know if you need any additional detail. Thank you!

![Screen Shot 2021-05-03 at 12 25 11 PM](https://user-images.githubusercontent.com/70535908/116917257-a521b700-ac0b-11eb-8f03-2869acb4b9b8.png)
![Screen Shot 2021-05-03 at 12 25 28 PM](https://user-images.githubusercontent.com/70535908/116917259-a652e400-ac0b-11eb-9ae7-08042b343cc7.png)

**Comment by MaTeMaTuK** [comment]
Hi @james-hafer,
Could you please check the latest version.

**Comment by james-hafer** [comment]
Apologies @MaTeMaTuK I didn't see the update come through. I just tested though and it looks great, thank you!
