### ISSUE TITLE
Scrolling doesn't work for touch devices

### ISSUE THREAD

**Issue by elimist3** [MaTeMaTuK/gantt-task-react#51]
Hello, thanks for creating this awesome library.

Is this library meant to work with touch events and mobile devices like the iPad? 
When I try to scroll the gantt chart on my iPad, nothing happens. I've tried to scroll on both Safari and mobile Chrome with the same results.

Any help would be appreciated!

**Comment by calin-vlasin-lateral** [comment]
I have this issue also, on mobile devices nothing happens at scrolling. Do you think that in near future a fix will be provided for this issue? Thanks and good job so far! Awesome library.

**Comment by calin-vlasin-lateral** [comment]
This issue is because of 
._CZjuD {
    overflow: hidden;
    font-size: 0;
    margin: 0;
    padding: 0;
}

overflow: hidden (it hides horizontall scrollbar) should be => overflow: auto. 

If you are using it in a react app just override this class in index.html
 <head>
    ........
    <style>
      ._CZjuD {
        overflow: auto !important;
        font-size: 0;
        margin: 0;
        padding: 0;
      }
    </style>
  </head>

**Comment by MaTeMaTuK** [comment]
I have modified scroll and tested on iPad mini. 
Maybe I will add toch options in the future
