### ISSUE TITLE
On Hourly view mode, Date mismatch.

### ISSUE THREAD

**Issue by mayankessar** [MaTeMaTuK/gantt-task-react#62]
On Hourly view mode, Date mentioned in header is one day more than the date mentioned on task date.

**Comment by MaTeMaTuK** [comment]
Hi @mayankessar,
Could you please add the screenshot ?

**Comment by mayankessar** [comment]
[](url
<img width="1440" alt="Screenshot 2022-05-24 at 5 17 08 PM" src="https://user-images.githubusercontent.com/19775973/170028062-98c05e5e-5724-49b5-9c24-a68293d0601c.png">
)

**Comment by MaTeMaTuK** [comment]
Fixed and publiched
