### ISSUE TITLE
Is possible have in one row more than one task?

### ISSUE THREAD

**Issue by irekrog** [MaTeMaTuK/gantt-task-react#66]
Hi @MaTeMaTuK 
Is this possible in the current version of component? Or to achieve this effect a library must be overridden?

**Comment by Kszysiek** [comment]
Hey @irekrog did you manage to add more than one task in a single row?

**Comment by irekrog** [comment]
@Kszysiek 
Nope, in gantt-task-react it is not possible. I think you can use this code and rewrite it. LICENSE is MIT so you can.

**Comment by MaTeMaTuK** [comment]
@irekrog, You able to modify chart from fork.
And I don't have plans for few items in the row for now.
