### ISSUE TITLE
Feature Request: View Modes for 3 Month (Quarter), 6 Month (Half Year), and Full Year

### ISSUE THREAD

**Issue by james-hafer** [MaTeMaTuK/gantt-task-react#73]
We would like to have additional view modes for tasks with longer durations. This is higher priority for us and we would like to know how we can move this up on the priority list for you. 

Happy to take this conversation offline, let me know what works for you!

**Comment by Graeme43** [comment]
Hi @james-hafer 

I've previously submitted a pull request for Year ViewMode #60 .

**Comment by james-hafer** [comment]
Thanks @Graeme43! Is that something you want me to review and test? I see it's been sitting there for a while.

**Comment by MaTeMaTuK** [comment]
Change has been merged
