### ISSUE TITLE
Namespace 'React' has no exported member 'SFC'. TS2694

### ISSUE THREAD

**Issue by garimahans15** [MaTeMaTuK/gantt-task-react#75]
Hi @MaTeMaTuK 
I am facing this error while installing this library. This is happening while installing `view-switcher`

cc  @Janlaywss @VikariiCGI @lisaavikarii 
````
TypeScript error in D:/TraxiemCB/traxiem/traxiem-ui/src/components/Gantt/view-switcher.tsx(9,34)
:
Namespace 'React' has no exported member 'SFC'. TS2694

```


7 | onViewModeChange: (viewMode: ViewMode) => void;
8 | };
> 9 | export const ViewSwitcher: React.SFC<ViewSwitcherProps> = ({
| ^
10 | onViewModeChange,
11 | onViewListChange,
12 | isChecked,`

**Comment by Janlaywss** [comment]
> Hi @MaTeMaTuK I am facing this error while installing this library. This is happening while installing `view-switcher`
> 
> cc @Janlaywss @VikariiCGI @lisaavikarii
> 
> ```
> TypeScript error in D:/TraxiemCB/traxiem/traxiem-ui/src/components/Gantt/view-switcher.tsx(9,34)
> :
> Namespace 'React' has no exported member 'SFC'. TS2694
> 
> ```
> 
> 
> 7 | onViewModeChange: (viewMode: ViewMode) => void;
> 8 | };
> > 9 | export const ViewSwitcher: React.SFC<ViewSwitcherProps> = ({
> | ^
> 10 | onViewModeChange,
> 11 | onViewListChange,
> 12 | isChecked,`
> ```

What's your `react` and `react-dom` version?

**Comment by garimahans15** [comment]
Thanks. It worked.

**Comment by suniltayal** [comment]
Hi,
We are able to render switcher tool bar but still there is an error in the file. It is saying React has no exported member of FC and tool bar is having very bad css rendered.

![image](https://user-images.githubusercontent.com/5518234/175893078-987cea3d-004b-4160-b83d-29f4d2c802ae.png)

**Comment by MaTeMaTuK** [comment]
Hi @suniltayal ,
What is the react version ? 
Have you use import "gantt-task-react/dist/index.css"; ?

**Comment by suniltayal** [comment]
Hi MaTeMaTuk,

My react version is "react": "^16.14.0",
and yes I have imported "gantt-task-react/dist/index.css"

**Comment by MaTeMaTuK** [comment]
I have updated react version. Please check
