### ISSUE TITLE
How can i change TaskListTable color?.

### ISSUE THREAD

**Issue by srknnn** [MaTeMaTuK/gantt-task-react#93]
Hi I have a  problem about to change color of the  TaskListTable component or gantt component color? Both this two option dont exist. Color change options are only available in the progressbar and tasks.
Can you help me about that?

**Comment by Maksketch** [comment]
TaskListTable is fairly customable, since you can build it from scratch and override the default. 
Check some of the answers in here:
https://github.com/MaTeMaTuK/gantt-task-react/issues/59

(You can build your own html-elements with css styling, instead of using Bootstraps, Row and Col)

**Comment by srknnn** [comment]
Thank you

**Comment by jiji-Bi** [comment]
there is one thing i'am not getting about this table ,why can't we make the rows editable ? i tried to implement my logic but the textfield on editmode won't just recieve input not firing onChange event from keyboard
