### ISSUE TITLE
Scroll position on "Today"

### ISSUE THREAD

**Issue by Maksketch** [MaTeMaTuK/gantt-task-react#96]
Hi MaTeMaTuk

Is it possible to add a setting where 'by default', the scrollbar-position is on "Today", for proper usability? 
I tried to override the scrollbars start-position with js, however it appears the scrollbar is not "just" a scrollbar around the parent element.

Hope to hear from you soon.

**Comment by MaTeMaTuK** [comment]
Hi @Maksketch,
Have you tried to use viewDate in https://github.com/MaTeMaTuK/gantt-task-react#displayoption  ?

**Comment by Maksketch** [comment]
Hi MaTeMaTuK
Thank you for the response! That was exactly what I was hoping for :)
